# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcGg9-ktjSAVSJsO3Of8CIupnX2_2qNj
"""

# Commented out IPython magic to ensure Python compatibility.

# ================== Master pipeline - Single-file Colab Script ==================
# Usage:
# 1) In Colab set your API key:
#    %env OPENAI_API_KEY=sk-...
# 2) Paste & run this whole cell.

# ---------------- Install Dependencies ----------------
!pip install --quiet openai python-pptx pillow gTTS natsort
!apt-get install -y ffmpeg fonts-dejavu-core > /dev/null

# ---------------- Imports ----------------
import os, json, textwrap, shutil, re, subprocess, time, math, random
from openai import OpenAI
from pptx import Presentation
from pptx.util import Pt, Inches
from PIL import Image, ImageDraw, ImageFont
from gtts import gTTS
from natsort import natsorted
from pathlib import Path
from multiprocessing import Pool, cpu_count

# ---------------- CONFIG ----------------


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") or ""

if not OPENAI_API_KEY:
    print("⚠️ No OPENAI_API_KEY found. Script will use fallback content (no LLM).")

client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

# Workspace
WORKDIR = Path("/content/fast_pipeline")
if WORKDIR.exists():
    shutil.rmtree(WORKDIR)

IMG_DIR = WORKDIR / "slide_images"
AUDIO_DIR = WORKDIR / "hinglish_audio"
TEMP_VID_DIR = WORKDIR / "temp_videos"
FINAL_VIDEO = WORKDIR / "final_output.mp4"

for d in [WORKDIR, IMG_DIR, AUDIO_DIR, TEMP_VID_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Visual/audio settings
IMG_W, IMG_H = 1280, 720  # 16:9
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
TITLE_FONT_SIZE = 40
BODY_FONT_SIZE = 22

# gTTS parallelism
MAX_TTS_WORKERS = min(6, max(1, cpu_count() - 1))
TTS_MAX_RETRIES = 2
TTS_BACKOFF_BASE = 1.3
TTS_PER_CALL_DELAY = 0.25

# ---------------- Helpers ----------------
def safe_parse_json(text):
    try:
        return json.loads(text)
    except Exception:
        m = re.search(r"(\{.*\}|\[.*\])", text, re.S)
        if not m:
            raise ValueError("Invalid JSON output from model.")
        return json.loads(m.group(1))

def extract_response_text(resp):
    try:
        if resp is None: return ""
        if hasattr(resp, "output_text"): return resp.output_text
        if hasattr(resp, "output") and len(resp.output) and hasattr(resp.output[0], "content"):
            try:
                return resp.output[0].content[0].text
            except Exception:
                return str(resp)
        if isinstance(resp, dict):
            if "output_text" in resp: return resp["output_text"]
            return json.dumps(resp)
        return str(resp)
    except Exception:
        return str(resp)

def print_progress(step_name, i=None, total=None):
    if i is None:
        print(f"[{step_name}]")
    else:
        print(f"[{step_name}] {i}/{total}")

def text_height(draw, text, font):
    bbox = draw.textbbox((0,0), text, font=font)
    return bbox[3] - bbox[1]

def get_audio_duration(path):
    try:
        cmd = ["ffprobe","-v","error","-show_entries","format=duration","-of","default=noprint_wrappers=1:nokey=1", path]
        res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, check=True)
        s = res.stdout.strip()
        return float(s) if s else 0.8
    except Exception:
        return 0.8
# ---------------- Step 1: Generate content (English + Hinglish) ----------------
def generate_content_bilingual(topic, max_slides=None):
    """
    Generates bilingual slides (English + Hinglish) in one API call.
    Teacher-style: definition, explanation, and mini examples on each slide.
    """
    prompt = f"""
You are an **AI Teacher** preparing slides to teach the topic "{topic}" to school/college students.
Write as if you are **explaining in class**: first explain what is the "{topic}", then explain step-by-step in simple words, then give a small example.

👉 Return JSON only with key "slides". Each slide object must have:
- "title_en"       : English title
- "body_en"        : English body text (12-15 lines, structured as Definition → Teacher Explanation → Example)
- "title_hinglish" : Hinglish title (Roman Hindi)
- "body_hinglish"  : Hinglish body (same points, but conversational teacher style)
- "tts_text"       : 2-5 lines Hinglish summary for speech narration

👉 Style rules:
- **Stage 1: Definition** — “What really is {topic}?” .
- **Stage 2: Explanation** — explain like a teacher, breaking into steps or simple language.
- **Stage 3: Example** — give a relatable mini example (cricket, mobile apps, YouTube, school life etc.).
- Use a **friendly teacher tone** (“Dekho baccho…”, “Socho agar…”, “Aapne kabhi notice kiya hai…?”).
- Avoid jargon; if needed, explain in plain language within 1 line.
- Hinglish should feel natural, not forced.
- Each slide’s body should flow like a mini-lesson, not just bullet points.

👉 Structure (10–16 slides total):
1. Title Slide — catchy title + tagline
2. What is {topic}? (Definition + Why important)
3–8. Core concept slides — each with Definition → Explanation → Example
9. Real-life Applications
10. Misconceptions/Doubts — 3–4 common mistakes corrected
11–12. Practice Q&A (at least 2 per slide, formatted Que.: … Ans.: …)
13. Recap (bullet summary of key takeaways)
14. Closing (motivational teacher note)

👉 Example format for slide bodies:
English body:
Definition: {topic} is …
Explanation: In simple terms, it means …
Example: Like when you use YouTube and see recommended videos, that’s …

Hinglish body:
Definition: {topic} ka matlab hai …
Explanation: Simple shabdon me iska matlab hai …
Example: Jaise aap YouTube pe recommendations dekhte ho, wahi {topic} ka use hai.

Return ONLY JSON with structure:
{{
  "slides": [
    {{
      "title_en": "...",
      "body_en": "Definition: ...\\nExplanation: ...\\nExample: ...",
      "title_hinglish": "...",
      "body_hinglish": "Definition: ...\\nExplanation: ...\\nExample: ...",
      "tts_text": "Short Hinglish narration"
    }}
  ]
}}
"""

    if max_slides:
        prompt += f"\n⚠️ Limit total slides to at most {max_slides}.\n"

    if client is None:
        print("⚠️ Using fallback content (no API key)")
        return {
            "slides": [
                {
                    "title_en": topic,
                    "body_en": f"Definition: {topic} overview\nExplanation: Basic idea\nExample: Example here",
                    "title_hinglish": topic,
                    "body_hinglish": f"Definition: {topic} overview\nExplanation: Basic idea\nExample: Example yaha",
                    "tts_text": f"{topic} overview"
                }
            ]
        }

    try:
        print_progress("Requesting bilingual slide content (API call)")
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role":"user","content":prompt}],
            temperature=0.35,
            response_format={"type":"json_object"}
        )
        raw = resp.choices[0].message.content.strip()
        parsed = safe_parse_json(raw)
        if "slides" in parsed:
            return parsed
        else:
            raise ValueError("Invalid JSON structure")
    except Exception as e:
        print("❌ Content generation failed:", e)
        return {
            "slides": [
                {
                    "title_en": topic,
                    "body_en": f"Definition: {topic} fallback\nExplanation: fallback\nExample: fallback",
                    "title_hinglish": topic,
                    "body_hinglish": f"Definition: {topic} fallback\nExplanation: fallback\nExample: fallback",
                    "tts_text": f"{topic} fallback"
                }
            ]
        }

# ---------------- Step 2: Save PPT ----------------
def save_ppt(slides, topic, language="hinglish"):
    prs = Presentation()
    prs.slide_width = Inches(13.333333)
    prs.slide_height = Inches(7.5)

    for i, s in enumerate(slides):
        slide = prs.slides.add_slide(prs.slide_layouts[1] if i>0 else prs.slide_layouts[0])
        title_shape = slide.shapes.title

        if language == "english":
            title_shape.text = s.get("title_en", "")
            body_text = s.get("body_en", "")
        else:
            title_shape.text = s.get("title_hinglish", "")
            body_text = s.get("body_hinglish", "")

        try:
            tf = slide.placeholders[1].text_frame
            tf.clear()
            tf.text = body_text
        except Exception:
            left = Inches(1); top = Inches(1.8); width = Inches(11.2); height = Inches(4.5)
            txBox = slide.shapes.add_textbox(left, top, width, height)
            txBox.text_frame.text = body_text

    out_path = WORKDIR / f"{topic.replace(' ','')}_{language}.pptx"
    prs.save(str(out_path))
    return str(out_path)

# ---------------- Step 3: Render Slide Images ----------------
def draw_pretty_slide(text, out_path):
    try:
        title_font = ImageFont.truetype(FONT_PATH, TITLE_FONT_SIZE)
        body_font = ImageFont.truetype(FONT_PATH, BODY_FONT_SIZE)
    except Exception:
        title_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    img = Image.new("RGB", (IMG_W, IMG_H), color=(255,255,255))
    draw = ImageDraw.Draw(img)

    # gradient background
    for y in range(IMG_H):
        t = y / float(max(1, IMG_H-1))
        r = int(248*(1-t)+225*t); g = int(251*(1-t)+235*t); b = int(255*(1-t)+250*t)
        draw.line([(0,y),(IMG_W,y)], fill=(r,g,b))

    bar_h = 90
    draw.rectangle([0,0,IMG_W,bar_h], fill=(30,60,120))

    lines = text.strip().splitlines()
    title = lines[0] if lines else ""
    body = "\n".join(lines[1:])

    if title:
        bbox = draw.textbbox((0,0), title, font=title_font)
        w = bbox[2]-bbox[0]; h = bbox[3]-bbox[1]
        draw.text(((IMG_W-w)/2, (bar_h-h)/2), title, font=title_font, fill=(255,255,255))

    x = 60; y = bar_h+20
    for paragraph in body.split("\n"):
        for line in textwrap.wrap(paragraph, width=60):
            draw.text((x,y), line, font=body_font, fill=(20,20,20))
            y += text_height(draw, line, body_font) + 6
            if y > IMG_H-60: break

    img.save(out_path, format="PNG")

# ---------------- Step 4: gTTS Worker ----------------
def tts_worker(task):
    idx, text, out_mp3 = task
    time.sleep(TTS_PER_CALL_DELAY * (idx % 3))
    try:
        gTTS(text=text or " ", lang='hi').save(out_mp3)
        return (idx, out_mp3, None)
    except Exception as e:
        print(f"⚠️ gTTS failed for slide {idx}: {e}")
        subprocess.run(["ffmpeg","-y","-f","lavfi","-i","anullsrc","-t","0.8", out_mp3],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return (idx, out_mp3, "fallback")

# ---------------- Step 5: Per-slide Video ----------------
def make_slide_video_audio_duration(args):
    img_path, audio_path, out_path = args
    dur = get_audio_duration(audio_path)
    cmd = [
        "ffmpeg","-y","-loop","1","-i",img_path,"-i",audio_path,
        "-map","0:v:0","-map","1:a:0",
        "-c:v","libx264","-r","25","-pix_fmt","yuv420p",
        "-c:a","aac","-b:a","192k","-t",f"{dur:.3f}", out_path
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out_path

# ---------------- Main Pipeline ----------------
def run_pipeline(topic_input=None, keep_temp=True):
    topic = topic_input or input("Enter the topic for your PPT: ").strip() or "Sample Topic"

    content_obj = generate_content_bilingual(topic)
    slides = content_obj.get("slides", [])
    slide_count = len(slides)
    print(f"Slides generated: {slide_count}")

    ppt_en = save_ppt(slides, topic, language="english")
    ppt_hi = save_ppt(slides, topic, language="hinglish")
    print("✅ PPTs saved:", ppt_en, ppt_hi)

    image_paths = []
    for i, s in enumerate(slides, start=1):
        img_text = (s.get("title_hinglish") or s.get("title_en","")) + "\n\n" + (s.get("body_hinglish") or s.get("body_en",""))
        out_path = IMG_DIR / f"slide_{i:03}.png"
        draw_pretty_slide(img_text, out_path)
        image_paths.append(str(out_path))

     # Audio (prefer narration, else fallback to full content)
    tasks = []
    for i, s in enumerate(slides, start=1):
        tts_text = s.get("tts_text")
        # If narration is missing or too short, use full Hinglish body
        if not tts_text or len(tts_text.split()) < 12:
            tts_text = s.get("body_hinglish") or s.get("body_en") or " "
        out_mp3 = str(AUDIO_DIR / f"slide_{i:03}.mp3")
        tasks.append((i, tts_text, out_mp3))


    results = []
    with Pool(processes=MAX_TTS_WORKERS) as pool:
        results = list(pool.imap_unordered(tts_worker, tasks))

    results_sorted = sorted(results, key=lambda x: x[0])
    audio_paths = [p for (_, p, _) in results_sorted]

    # Slide videos
    slide_video_tasks = [(img,aud,str(TEMP_VID_DIR/f"part_{i:03}.mp4")) for i,(img,aud) in enumerate(zip(image_paths,audio_paths),start=1)]
    with Pool(processes=min(4, cpu_count()-1)) as pool:
        slide_vids = pool.map(make_slide_video_audio_duration, slide_video_tasks)

    concat_list_path = WORKDIR / "videos_list.txt"
    with open(concat_list_path, "w") as f:
        for v in slide_vids:
            f.write(f"file '{v}'\n")

    ff_concat_cmd = [
        "ffmpeg","-y","-f","concat","-safe","0","-i",str(concat_list_path),
        "-c:v","libx264","-preset","veryfast","-crf","18","-c:a","aac","-b:a","192k", str(FINAL_VIDEO)
    ]
    subprocess.run(ff_concat_cmd, check=True)
    print("🎬 Final video saved:", FINAL_VIDEO)

    return {
        "pptx_english": ppt_en,
        "pptx_hinglish": ppt_hi,
        "video": str(FINAL_VIDEO),
        "slides": slide_count
    }

# ---------------- Run ----------------
if __name__ == "__main__":
    result = run_pipeline(None, keep_temp=True)
    print(json.dumps(result, indent=2))